pipeline {
    agent any

    environment {
        REGISTRY = 'localhost:5000' 
        IMAGE_NAME = 'myimage'            
        TAG = 'latest'                      
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    def imageTag = "${REGISTRY}/${IMAGE_NAME}:${TAG}"
                    sh "docker build -f Dockerfile -t ${imageTag} ."
                }
            }
        }

        stage('Tagging Image') {
            steps {
                script {
                    def currentDate = new Date().format("yyyyMMddHHmmss", TimeZone.getTimeZone("UTC"))
                    def progressiveTag = "${REGISTRY}/${IMAGE_NAME}:${currentDate}"
                    sh "docker tag ${REGISTRY}/${IMAGE_NAME}:${TAG} ${progressiveTag}"
                }
            }
        }

        stage('Push Image') {
            steps {
                script {
                    def progressiveTag = "${REGISTRY}/${IMAGE_NAME}:${new Date().format('yyyyMMddHHmmss')}"
                    sh "docker push ${progressiveTag}"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}


