pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-credentials'
        REGISTRY = 'docker-registry'
        IMAGE_NAME = 'myimage_step5'
        TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir ('step5') {
                    script {
                        def imageTag = "${REGISTRY}/${IMAGE_NAME}:${TAG}"
                        docker.build(imageTag, '.')
                    }
                }
            }
        }

        stage('Tagging Image') {
            steps {
                script {
                    def currentDate = new Date().format("yyyyMMddHHmmss", TimeZone.getTimeZone("UTC"))
                    def progressiveTag = "${REGISTRY}/${IMAGE_NAME}:${currentDate}"
                    sh "docker tag ${REGISTRY}/${IMAGE_NAME}:${TAG} ${progressiveTag}"
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    if (env.DOCKERHUB_CREDENTIALS) {
                        docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS}") {
                            def image = docker.image("${IMAGE_NAME}:${TAG}")
                            try {
                                image.push()
                            } catch (Exception e) {
                                error "Docker push failed: ${e.message}"
                            }
                        }
                    } 
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
