- name: Costruzione e avvio dei container Docker
  hosts: localhost
  tasks:
    - name: Costruire l'immagine Docker per Ubuntu
      community.docker.docker_image:
        source: build
        build:
          path: ./ubuntu
        name: ssh_ubuntu
        tag: latest

    - name: Avviare il container Ubuntu
      community.docker.docker_container:
        name: container_ubuntu
        image: ssh_ubuntu:latest
        state: started
        ports:
          - "2201:22"
        restart_policy: always
        privileged: true
